In [33]:
import pandas as pd
import numpy as np
import matplotlib as plt


df = pd.read_csv('../Data/Clean/googleplaystore_clean.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [34]:
df.shape

(8892, 13)

In [35]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8892 entries, 0 to 8891
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8892 non-null   str
 1   Category        8892 non-null   str
 2   Rating          8892 non-null   float64
 3   Reviews         8892 non-null   int64
 4   Size            8892 non-null   str
 5   Installs        8892 non-null   int64
 6   Type            8892 non-null   str
 7   Price           8892 non-null   float64
 8   Content Rating  8892 non-null   str
 9   Genres          8892 non-null   str
 10  Last Updated    8892 non-null   str
 11  Current Ver     8892 non-null   str
 12  Android Ver     8892 non-null   str
dtypes: float64(2), int64(2), str(9)
memory usage: 903.2 KB

In [37]:
df.describe()

            Rating       Reviews      Installs        Price
count  8892.000000  8.892000e+03  8.892000e+03  8892.000000
mean      4.187877  4.727764e+05  1.648965e+07     0.963155
std       0.522377  2.905052e+06  8.637600e+07    16.189341
min       1.000000  1.000000e+00  1.000000e+00     0.000000
25%       4.000000  1.640000e+02  1.000000e+04     0.000000
50%       4.300000  4.714500e+03  5.000000e+05     0.000000
75%       4.500000  7.126675e+04  5.000000e+06     0.000000
max       5.000000  7.815831e+07  1.000000e+09   400.000000

In [38]:
df[df['Price'] == 400]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3749,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.3M,10000,Paid,400.0,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up

In [39]:
df.describe(include=['object','string'])

,App,Category,Size,Type,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,8892,8892,8892,8892,8892,8892,8892,8892,8892
unique,8196,33,414,2,6,115,1300,2638,31
top,ROBLOX,FAMILY,Varies with device,Free,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1718,1468,8279,7095,733,291,1262,1989

In [40]:
df['Category'].value_counts().head(10)

Category
FAMILY             1718
GAME               1074
TOOLS               734
PRODUCTIVITY        334
FINANCE             317
PERSONALIZATION     310
COMMUNICATION       307
LIFESTYLE           305
PHOTOGRAPHY         304
MEDICAL             302
Name: count, dtype: int64

In [41]:
df['Type'].value_counts()

Type
Free    8279
Paid     613
Name: count, dtype: int64

In [44]:
df['Content Rating'].value_counts()

Content Rating
Everyone           7095
Teen               1022
Mature 17+          411
Everyone 10+        360
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [46]:
df.groupby('Category')['Rating'].mean().head()

Category
ART_AND_DESIGN         4.358065
AUTO_AND_VEHICLES      4.190411
BEAUTY                 4.278571
BOOKS_AND_REFERENCE    4.347458
BUSINESS               4.102593
Name: Rating, dtype: float64